### ISSUE TITLE
run_calibration failing on PDF

### ISSUE THREAD

**Issue by DanOlds** [xpdAcq/mission-control#155]
Clicking on the rings during a calibration procedure (executed using the run_calibration command) throws a nasty error, and doesn't work.  Currently, users cannot use the xpdan real-time pipeline because of this issue.

## Expected Behavior

Clicking on rings should cause them to be selected, not throw a pyFAI error.

## Current Behavior

Below is an example of what happens when the plot is clicked upon:

ERROR:pyFAI.peak_picker:ControlPoint.load: No such file /tmp/tmpqw0cgcba/from_calib_func.npt
/home/xf28id1/conda_envs/collection-2018-3.2-PDF/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  warnings.warn(message, mplDeprecation, stacklevel=1)
Please press enter when you are happy with your selection
Traceback (most recent call last):
  File "/home/xf28id1/conda_envs/collection-2018-3.2-PDF/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 387, in process
    proxy(*args, **kwargs)
  File "/home/xf28id1/conda_envs/collection-2018-3.2-PDF/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 227, in __call__
    return mtd(*args, **kwargs)
  File "/home/xf28id1/conda_envs/collection-2018-3.2-PDF/lib/python3.6/site-packages/pyFAI/peak_picker.py", line 549, in onclick
    new_grp(event)
  File "/home/xf28id1/conda_envs/collection-2018-3.2-PDF/lib/python3.6/site-packages/pyFAI/peak_picker.py", line 419, in new_grp
    None, self.massif_contour)
  File "/home/xf28id1/conda_envs/collection-2018-3.2-PDF/lib/python3.6/site-packages/pyFAI/massif.py", line 124, in find_peaks
    region = self.calculate_massif(x)
  File "/home/xf28id1/conda_envs/collection-2018-3.2-PDF/lib/python3.6/site-packages/pyFAI/massif.py", line 109, in calculate_massif
    if labeled[x[0], x[1]] != labeled.max():
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

### Priority

This is a high priority issue.  Auto-reduction is not possible, and we're falling back on fit2d.

## Your Environment

This is occuring on the PDF beamline, xf28id1-ws2 computer, when logged in as xf28id1.

**Comment by CJ-Wright** [comment]
Can you run `conda update pyfai` in the working environment?

**Comment by CJ-Wright** [comment]
I believe this has been fixed now with `pyfai=0.15`
