### ISSUE TITLE
Tramp did not save file

### ISSUE THREAD

**Issue by adelezh** [xpdAcq/mission-control#189]
Error message from save_server window:
```python
Saving file to 
Exception in callback Dispatcher.process(<DocumentNames.event: 'event'>, {'data': {'config': <diffpy.pdfge...x7f1a066e4ef0>, 'gr': array([ 0.   ... -0.15004169]), 'r': array([0.000e...   3.000e+01])}, 'descriptor': 'abf7ce31-b18...-c3efbaae30fa', 'filled': {'config': True, 'gr': True, 'r': True}, 'seq_num': 4, ...})
handle: <Handle Dispatcher.process(<DocumentNames.event: 'event'>, {'data': {'config': <diffpy.pdfge...x7f1a066e4ef0>, 'gr': array([ 0.   ... -0.15004169]), 'r': array([0.000e...   3.000e+01])}, 'descriptor': 'abf7ce31-b18...-c3efbaae30fa', 'filled': {'config': True, 'gr': True, 'r': True}, 'seq_num': 4, ...})>
Traceback (most recent call last):
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/bluesky/run_engine.py", line 2344, in process
    exceptions = self.cb_registry.process(name, name.name, doc)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/bluesky/utils.py", line 334, in process
    func(*args, **kwargs)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/bluesky/utils.py", line 415, in __call__
    return mtd(*args, **kwargs)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/xpdan/vend/callbacks/core.py", line 67, in __call__
    ret = getattr(self, name)(doc)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/xpdan/vend/callbacks/core.py", line 482, in event
    cb("event", doc)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/xpdan/vend/callbacks/core.py", line 67, in __call__
    ret = getattr(self, name)(doc)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/xpdan/callbacks.py", line 245, in event
    doc = super().event(doc)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/xpdan/callbacks.py", line 169, in event
    os.makedirs(os.path.dirname(filename), exist_ok=True)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
Saving file to 
Exception in callback Dispatcher.process(<DocumentNames.event: 'event'>, {'data': {'mean': array([0.9299...  0.        ]), 'q': array([2.8525...02741253e+01]), 'tth': array([4.7363...71224990e+01])}, 'descriptor': 'a7f948d9-3bb...-0acc93374f72', 'filled': {'mean': True, 'q': True, 'tth': True}, 'seq_num': 4, ...})
handle: <Handle Dispatcher.process(<DocumentNames.event: 'event'>, {'data': {'mean': array([0.9299...  0.        ]), 'q': array([2.8525...02741253e+01]), 'tth': array([4.7363...71224990e+01])}, 'descriptor': 'a7f948d9-3bb...-0acc93374f72', 'filled': {'mean': True, 'q': True, 'tth': True}, 'seq_num': 4, ...})>
Traceback (most recent call last):
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/bluesky/run_engine.py", line 2344, in process
    exceptions = self.cb_registry.process(name, name.name, doc)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/bluesky/utils.py", line 334, in process
    func(*args, **kwargs)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/bluesky/utils.py", line 415, in __call__
    return mtd(*args, **kwargs)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/xpdan/vend/callbacks/core.py", line 67, in __call__
    ret = getattr(self, name)(doc)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/xpdan/vend/callbacks/core.py", line 482, in event
    cb("event", doc)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/xpdan/vend/callbacks/core.py", line 67, in __call__
    ret = getattr(self, name)(doc)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/xpdan/callbacks.py", line 197, in event
    doc = super().event(doc)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/xpdan/callbacks.py", line 169, in event
    os.makedirs(os.path.dirname(filename), exist_ok=True)
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by CJ-Wright** [comment]
Thank you for reporting!
Did this happen for all the files or just the G(r)?

**Comment by CJ-Wright** [comment]
Also do you have the start uid for the data that caused this?

**Comment by adelezh** [comment]
It didn’t save anything, didn’t create the folder with sample name

**Comment by CJ-Wright** [comment]
Can you restart the save server? Does the problem persist after restarting?

**Comment by adelezh** [comment]
Users are running experiment now, could not restart save server, but the same thing happened at PDF too, restart save_server did not help.
    On Friday, June 7, 2019, 2:02:20 PM EDT, Christopher J. Wright <notifications@github.com> wrote:  
 
 
Can you restart the save server? Does the problem persist after restarting?

**Comment by CJ-Wright** [comment]
When did this happen at PDF? (I'm trying to gather the details so I can debug this)

**Comment by adelezh** [comment]
I think it was May 30? They were using Cryostat. Today we are using Linkam 

    On Friday, June 7, 2019, 2:06:14 PM EDT, Christopher J. Wright <notifications@github.com> wrote:  
 
 
When did this happen at PDF? (I'm trying to gather the details so I can debug this)

**Comment by CJ-Wright** [comment]
note to self: use this uid `cce2a976-c3e84bb1-bde5ad224c0da722`
